name: abakus_one_v2
description: "Abakus Bowl Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  battery_plus: ^7.1.1
  connectivity_plus: ^7.3.1
  firebase_app_check: ^0.4.5+2
  firebase_core: ^4.12.1
  firebase_remote_config: ^6.5.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^10.3.1
  geolocator: ^14.0.3
  go_router: ^17.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboarding/
    - assets/images/menu/
    - assets/images/products/
    - assets/images/products/Proteinler/
    - assets/images/products/Karbonhidratlar/
    - assets/images/products/Salatalar/
    - assets/images/products/Sebzeler/
    - assets/images/products/Meyveler/
    - assets/images/products/Turşular/
    - assets/images/products/Peynirler/
    - assets/images/products/Diğerleri/
    - assets/images/products/Soslar/
    - assets/images/bowl/
    - assets/images/bowl/layers/