/// The kind of human-meaningful courier-operations action a
/// [CourierOperationalAuditEntry] records — narrower than
/// [CourierEventType] (no connectivity/heartbeat events here).
///
/// Sprint 5C (Courier Dispatch & Operations Center) adds
/// `dispatchQueueManualOverride` onward.
enum CourierAuditEventType {
  courierActivated,
  courierSuspended,
  courierArchived,
  shiftRequested,
  shiftApproved,
  shiftRejected,
  shiftStarted,
  shiftEnded,
  shiftCompleted,
  shiftCancelled,
  availabilityChanged,
  deliveryCreated,
  assignmentOffered,
  assignmentAccepted,
  assignmentRejected,
  manuallyAssigned,
  reassigned,
  assignmentCancelled,
  restaurantArrivalConfirmed,
  packagePickedUp,
  deliveryStarted,
  customerArrivalConfirmed,
  deliveryCompleted,
  deliveryFailed,
  geofenceOverridden,
  customerContactAction,
  failureResponsibilityReviewed,
  compensationProfileCreated,
  shiftScheduled,
  deliveryEarningsCalculated,
  shiftEarningsCalculated,
  earningsAdjustmentCreated,
  earningsMarkedPaid,
  locationAvailabilityChanged,
  locationEmergencyOverrideGranted,
  locationTrackingStarted,
  locationTrackingStopped,
  locationHistoryReset,
  locationPermissionChanged,
  fraudSignalDetected,
  dispatchQueueManualOverride,
  deliverySequenceReordered,
  sameDestinationGrouped,
  shiftTransferred,
  temporaryPackageBlockingChanged,
  courierMessageSent,
  broadcastMessageSent,
  emergencyMessageSent,
  emergencyMessageAcknowledged,
}
