import '../../../../core/config/asset_paths.dart';

/// Resolves a Bowl Builder ingredient's `imageKey` to an actual bundled
/// asset path, or `null` if no image exists for that key yet — mirrors
/// `menu/domain/services/menu_image_resolver.dart`'s exact contract and
/// discipline (strict, exact-match only; never guess a path).
///
/// [_imagesByKey] was generated by scanning every file under
/// `assets/images/products/<Kategori>/` (Faz 8.1, 2026-07-24) and keying
/// each one by its own filename, with no category prefix — the same slug
/// [BowlBuilderIngredient.imageKey] is expected to already carry. The
/// physical subfolder a photo lives in (named after the *photo's own*
/// subject, e.g. "Sebzeler/avokado.png") doesn't have to match the
/// ingredient's Bowl Builder category (e.g. Avokado is catalogued under
/// "Diğerleri") — only the filename has to match, since that's genuinely
/// what determines whether the picture shows the right thing.
///
/// Not every ingredient has a matching photo yet, and not every photo is
/// currently claimed by an ingredient — see `findMissingImageKeys` and
/// `findOrphanedImageKeys`. Unmatched ingredients correctly fall back to
/// [ProductImage]'s placeholder. Adding a missing photo later is a
/// two-step, code-only-in-the-sense-of-one-line change: drop the PNG into
/// its category folder under `assets/images/products/`, then add an entry
/// to [_imagesByKey] here. No other file changes — not the catalog, not
/// the UI, not the provider.
abstract final class IngredientImageResolver {
  IngredientImageResolver._();

  /// Filename (no extension) -> path relative to
  /// [AssetPaths.productsImageDirectory]. The map key equals the real
  /// filename in every entry except one confirmed, documented exception
  /// (Jalapeño/'jalepeno_tursusu.png' below) — never add another one
  /// without the same kind of explicit, product-confirmed note.
  static const Map<String, String> _imagesByKey = {
    // ---- Diğerleri ----
    // Generic, unlabeled filenames from an image-generation batch — none of
    // them can be confidently tied to a specific ingredient by name, so
    // none are registered. Kept out on purpose; see `findOrphanedImageKeys`.

    // ---- Karbonhidratlar ----
    'kekikli_makarna': 'Karbonhidratlar/kekikli_makarna.png',
    'kinoa': 'Karbonhidratlar/kinoa.png',
    'kori_makarna': 'Karbonhidratlar/kori_makarna.png',
    'kuskus': 'Karbonhidratlar/kuskus.png',
    'meksika_pilavi': 'Karbonhidratlar/meksika_pilavi.png',
    'pesto_makarna': 'Karbonhidratlar/pesto_makarna.png',
    'pirinc_pilavi': 'Karbonhidratlar/pirinc_pilavi.png',
    'sehriyeli_bulgur_pilavi': 'Karbonhidratlar/sehriyeli_bulgur_pilavi.png',
    'tereyeagli_makarna': 'Karbonhidratlar/tereyeagli_makarna.png',

    // ---- Meyveler ----
    'ananas': 'Meyveler/ananas.png',
    'kizarmis_ananas': 'Meyveler/kizarmis_ananas.png',
    'muz': 'Meyveler/muz.png',
    'nar': 'Meyveler/nar.png',
    'yaban_mersini': 'Meyveler/yaban_mersini.png',

    // ---- Peynirler ----
    'beyaz_peynir': 'Peynirler/beyaz_peynir.png',
    'cheddar_peyniri': 'Peynirler/cheddar_peyniri.png',
    'parmesan_peyniri': 'Peynirler/parmesan_peyniri.png',
    'tulum_peyniri': 'Peynirler/tulum_peyniri.png',

    // ---- Proteinler ----
    'aci_tavuk': 'Proteinler/aci_tavuk.png',
    'cirpilmis_yumurta': 'Proteinler/cirpilmis_yumurta.png',
    'citir_tavuk': 'Proteinler/citir_tavuk.png',
    'citir_tofu': 'Proteinler/citir_tofu.png',
    'dana_antrikot_fume': 'Proteinler/dana_antrikot_fume.png',
    'dana_bonfile': 'Proteinler/dana_bonfile.png',
    'falafel': 'Proteinler/falafel.png',
    'haslanmis_yumurta': 'Proteinler/haslanmis_yumurta.png',
    'izgara_kofte': 'Proteinler/izgara_kofte.png',
    'izgara_tavuk': 'Proteinler/izgara_tavuk.png',
    'karisik_sebze': 'Proteinler/karisik_sebze.png',
    'kori_tavuk': 'Proteinler/kori_tavuk.png',
    'somon_fume': 'Proteinler/somon_fume.png',
    'soya_tavuk': 'Proteinler/soya_tavuk.png',
    'tatli_eksi_tavuk': 'Proteinler/tatli_eksi_tavuk.png',
    'teriyaki_tavuk': 'Proteinler/teriyaki_tavuk.png',
    'ton_baligi': 'Proteinler/ton_baligi.png',

    // ---- Salatalar ----
    'coban_salata': 'Salatalar/coban_salata.png',
    'mevsim_salata': 'Salatalar/mevsim_salata.png',

    // ---- Sebzeler ----
    'avokado': 'Sebzeler/avokado.png',
    'beyaz_lahana': 'Sebzeler/beyaz_lahana.png',
    'ceri_domates': 'Sebzeler/ceri_domates.png',
    'domates': 'Sebzeler/domates.png',
    'edamame': 'Sebzeler/edamame.png',
    'izgara_havuc': 'Sebzeler/izgara_havuc.png',
    'izgara_kabak': 'Sebzeler/izgara_kabak.png',
    'izgara_kapya_biber': 'Sebzeler/izgara_kapya_biber.png',
    'kapya_biber': 'Sebzeler/kapya_biber.png',
    'karamelize_sogan': 'Sebzeler/karamelize_sogan.png',
    'kuru_sogan': 'Sebzeler/kuru_sogan.png',
    'lolorosso': 'Sebzeler/lolorosso.png',
    'mantar_sote': 'Sebzeler/mantar_sote.png',
    'marul': 'Sebzeler/marul.png',
    'maydanoz': 'Sebzeler/maydanoz.png',
    'meksika_fasulyesi': 'Sebzeler/meksika_fasulyesi.png',
    'misir': 'Sebzeler/misir.png',
    'rende_havuc': 'Sebzeler/rende_havuc.png',
    'roka': 'Sebzeler/roka.png',
    'salatalik': 'Sebzeler/salatalik.png',
    'susamli_corek_otlu_salatalik': 'Sebzeler/susamli_corek_otlu_salatalik.png',
    'taze_sogan': 'Sebzeler/taze_sogan.png',
    'zeytin': 'Sebzeler/zeytin.png',

    // ---- Soslar ----
    'aci_sos': 'Soslar/aci_sos.png',
    'balli_hardal': 'Soslar/balli_hardal.png',
    'barbeku_sos': 'Soslar/barbeku_sos.png',
    'caesar_sos': 'Soslar/caesar_sos.png',
    'hardal_sos': 'Soslar/hardal_sos.png',
    'humus': 'Soslar/humus.png',
    'mayonez': 'Soslar/mayonez.png',
    'nar_eksisi': 'Soslar/nar_eksisi.png',
    'pesto_sos': 'Soslar/pesto_sos.png',
    'soya_sos': 'Soslar/soya_sos.png',
    'sriracha_sos': 'Soslar/sriracha_sos.png',
    'sweet_chilli': 'Soslar/sweet_chilli.png',
    'truflu_mayonez': 'Soslar/truflu_mayonez.png',
    'yogurt_sos': 'Soslar/yogurt_sos.png',
    'zeytinyag_limon_sos': 'Soslar/zeytinyag_limon_sos.png',

    // ---- Turşular ----
    'kornison_tursu': 'Turşular/kornison_tursu.png',
    'mor_lahana_tursusu': 'Turşular/mor_lahana_tursusu.png',
    // 'jalepeno_tursusu.png' is the confirmed photo for the "Jalapeño"
    // ingredient (imageKey 'jalapeno') — its filename is a legitimate
    // exception to the "map key == filename" convention above: the file
    // itself is correct and stays exactly as-is (misspelling and
    // "_tursusu" suffix included), only this one entry's key is the
    // ingredient's own slug rather than the raw filename (product
    // confirmation, 2026-07-24).
    'jalapeno': 'Turşular/jalepeno_tursusu.png',
  };

  static String? resolve(String imageKey) {
    final relativePath = _imagesByKey[imageKey];
    if (relativePath == null) return null;
    return '${AssetPaths.productsImageDirectory}$relativePath';
  }

  /// Every key in [imageKeys] that has no matching bundled asset — i.e.
  /// ingredients that will show [ProductImage]'s placeholder today.
  static List<String> findMissingImageKeys(Iterable<String> imageKeys) {
    return imageKeys
        .toSet()
        .where((key) => !_imagesByKey.containsKey(key))
        .toList()
      ..sort();
  }

  /// Every bundled photo in [_imagesByKey] that isn't referenced by any of
  /// [referencedImageKeys] — photos that exist but no current ingredient
  /// claims. Intended for a one-off report, not per-frame use.
  static List<String> findOrphanedImageKeys(
    Iterable<String> referencedImageKeys,
  ) {
    final referenced = referencedImageKeys.toSet();
    return _imagesByKey.keys.where((key) => !referenced.contains(key)).toList()
      ..sort();
  }
}
