import { onDocumentCreated } from "firebase-functions/v2/firestore";
import { getFirestore, Timestamp } from "firebase-admin/firestore";
import type { Firestore } from "firebase-admin/firestore";
import * as logger from "firebase-functions/logger";
import { TENANT_CUSTOMERS_COLLECTION } from "./completeCustomerProfile";
import {
  LOYALTY_ACCOUNTS_COLLECTION,
  LOYALTY_LEDGER_ENTRIES_COLLECTION,
  deriveLoyaltyLedgerEntryId,
  type LoyaltyLedgerEntry,
} from "./loyaltyLedger";
import {
  loyaltyPolicyDocRef,
  loyaltyPolicyBootstrapRef,
  readLoyaltyPolicyInTransaction,
  writeDefaultLoyaltyPolicyInTransaction,
  combineCarryWithEarning,
  parseCarryComponent,
  formatCarryComponent,
  ZERO_BONCUK_CARRY,
  type BoncukFraction,
} from "./loyaltyPolicy";
import type { LoyaltyAccountData } from "./getCustomerLoyaltySnapshot";
import { hasServerPricingAuthority } from "./orderPricingAuthority";

/**
 * `loyaltyOrderEarning` — Boncuk Loyalty Program P2A (2026-08-20), security
 * fix 2026-08-21, aggregate/debt-based rewrite P2B-B (2026-08-22),
 * Configurable Loyalty Economics (2026-08-24), corrected same-day for
 * exact-ratio math, and corrected AGAIN for the Fractional Entitlement
 * Carry model below (the per-policy-version "earning epoch" design that
 * preceded it was rejected for forfeiting economically-earned partial
 * progress on a policy change).
 *
 * Consumes the existing `orderEvents/{orderId}-completed` transactional
 * outbox record (`onOrderCompleted.ts`, Sprint 9F/ADR-026 — untouched by
 * this phase) to award real Boncuk for a canonical COMPLETED order.
 * Deliberately an asynchronous CONSUMER, never folded into
 * `onOrderCompleted.ts`'s own update-trigger transaction — mirrors
 * `reservationNotificationDelivery.ts`'s established outbox-consumer split
 * (thin `onDocumentCreated` trigger + an independently-testable business
 * function) rather than inventing a new pattern. This is NOT a second
 * completion trigger on `orders/{orderId}` — it only ever reacts to the
 * outbox record `onOrderCompleted.ts` already writes.
 *
 * **Locked scope (P2A architect decision, 2026-08-20) — "earn only from
 * server-trusted channels."** See [LOYALTY_EARNING_ELIGIBLE_CHANNELS] and
 * `docs/business_rules.md` `BR-LOYALTY-012`.
 *
 * **Security fix (2026-08-21) — channel alone is never sufficient.**
 * Earning additionally requires [hasServerPricingAuthority] on the order
 * document. See `functions/src/orderPricingAuthority.ts` and
 * `BR-LOYALTY-013`.
 *
 * **Fractional Entitlement Carry model (this correction).** A customer's
 * unconverted partial progress toward their next Boncuk is represented as
 * an EXACT, POLICY-INDEPENDENT FRACTION of one Boncuk —
 * `loyaltyAccounts.earningCarryNumerator`/`earningCarryDenominator`
 * (canonical non-negative-integer decimal strings — see
 * `loyaltyPolicy.ts`'s `BoncukFraction`/`parseCarryComponent`/
 * `formatCarryComponent`) — never as a currency-denominated remainder
 * scoped to one policy version. Every earning event, regardless of which
 * policy happens to be active, does exactly one thing: combine the
 * account's EXISTING carry with the EXACT fractional entitlement this
 * order's own eligible spend earns under the policy active RIGHT NOW
 * (`loyaltyPolicy.ts`'s `combineCarryWithEarning` — exact `BigInt`
 * fraction arithmetic, `floor` applied exactly once to the combined exact
 * rational total). There is no "epoch," no reset, and no branch that ever
 * discards or reinterprets the carry — a policy change can only ever
 * affect the RATE at which BRAND-NEW spend converts into fractional
 * Boncuk from that point forward.
 *
 * This directly satisfies both halves of the correction's own requirement,
 * simultaneously, by construction — not as two separate mechanisms that
 * have to be kept in sync:
 * - `OLD_PROGRESS_RERATED = NO` — a policy change never touches the
 *   existing carry; it only supplies the ratio for whatever spend happens
 *   AFTER the change.
 * - `OLD_PROGRESS_FORFEITED = NO` (equivalently `OLD_PROGRESS_CAN_COMPLETE
 *   = YES`) — the carry from before a policy change combines EXACTLY with
 *   new spend after it; if together they reach a whole Boncuk, the
 *   customer receives it, precisely as if their whole history had been
 *   tracked in Boncuk terms from day one (because, informally, it always
 *   was — currency was only ever a description of HOW that Boncuk-value
 *   was earned, not a scope the progress itself lives inside).
 * `OLD_PROGRESS_AUDIT_PRESERVED = YES` continues to hold structurally: no
 * ledger entry is ever rewritten, and every entry snapshots its own
 * before/after carry, ratio, and policy version verbatim.
 *
 * **O(1) reversal correction (this pass) — `validOrderEntitlementBoncuk`.**
 * `loyaltyAccounts` also carries `validOrderEntitlementBoncuk`, the
 * currently valid WHOLE Boncuk entitlement generated by non-reversed order
 * spend — distinct from `lifetimeEarned` (monotonic, never decremented by
 * a reversal). Every earning event increments it by exactly
 * `calc.wholeBoncukEarned` (the SAME value already computed for the
 * ledger/spendable-credit/debt-repayment logic — no extra computation).
 * This field exists so a future reversal writer never needs to replay any
 * ledger entry other than the one being reversed — see
 * `loyaltyReversalMath.ts`'s own doc comment for the O(1) formula and its
 * proof of equivalence to a full historical replay.
 *
 * **Known, disclosed limitation**: no currently shipping Cloud Function or
 * client write path ever transitions a real order to `status: "completed"`
 * — only test-harness code does. This consumer is real, fully tested
 * against the existing `orderEvents`/`onOrderCompleted.ts` contract, but
 * production execution is unreachable until a canonical server-side
 * order-completion transition exists (out of scope here).
 */

// -----------------------------------------------------------------------
// Earning eligibility — closed allow-list, not a blocklist. A channel not
// explicitly listed here never earns, by default, including any future
// channel introduced without this list being deliberately revisited.
// -----------------------------------------------------------------------

export const LOYALTY_EARNING_ELIGIBLE_CHANNELS = [
  "takeaway",
  "delivery",
  "reservationPreorder",
] as const;
type LoyaltyEarningEligibleChannel = (typeof LOYALTY_EARNING_ELIGIBLE_CHANNELS)[number];

function isEligibleChannel(channel: unknown): channel is LoyaltyEarningEligibleChannel {
  return (
    typeof channel === "string" &&
    (LOYALTY_EARNING_ELIGIBLE_CHANNELS as readonly string[]).includes(channel)
  );
}

/**
 * The single, isolated seam for computing the eligible net spend basis —
 * BR-LOYALTY §3: "eligible net spend after campaign/coupon discount." See
 * the P2A doc comment history for the full reasoning — unchanged by P2B-B.
 *
 * **Boncuk Loyalty P4-B (2026-08-22) — BR-LOYALTY-004, Boncuk-paid amount
 * never earns.** When the order carries a valid `boncukRedemption`
 * snapshot, the eligible basis excludes the redeemed value:
 * `eligibleNetSpendMinorUnits = pricing.grandTotal.minorUnits -
 * boncukRedemption.valueMinorUnits`. Safe to trust `boncukRedemption`
 * verbatim here ONLY because this function is called exclusively after the
 * order has already proven `hasServerPricingAuthority` (see this file's
 * own call site) — `firestore.rules`' `clientOrderCreateOmitsBoncukRedemption()`
 * guarantees no client-authored order create can ever carry this field at
 * all, so a server-pricing-authoritative order's `boncukRedemption` (if
 * present) was necessarily written by `submitTakeawayOrder.ts`'s own
 * trusted transaction, never forged. A present-but-malformed block still
 * fails this function closed (`null`), same "do not silently approximate"
 * discipline as every other check here. No redemption present →
 * unchanged behavior.
 */
export function resolveEligibleNetSpendMinorUnits(
  orderData: FirebaseFirestore.DocumentData,
): number | null {
  const pricing = orderData.pricing;
  if (!pricing || typeof pricing !== "object") return null;
  const grandTotal = (pricing as Record<string, unknown>).grandTotal;
  if (!grandTotal || typeof grandTotal !== "object") return null;
  const minorUnits = (grandTotal as Record<string, unknown>).minorUnits;
  const currencyCode = (grandTotal as Record<string, unknown>).currencyCode;
  if (typeof minorUnits !== "number" || !Number.isInteger(minorUnits) || minorUnits < 0) {
    return null;
  }
  if (currencyCode !== "TRY") return null;

  const boncukRedemption = orderData.boncukRedemption;
  if (boncukRedemption === null || boncukRedemption === undefined) {
    return minorUnits;
  }
  if (typeof boncukRedemption !== "object") return null;
  const valueMinorUnits = (boncukRedemption as Record<string, unknown>).valueMinorUnits;
  if (typeof valueMinorUnits !== "number" || !Number.isInteger(valueMinorUnits) || valueMinorUnits < 0) {
    return null;
  }
  const eligibleNetSpendMinorUnits = minorUnits - valueMinorUnits;
  if (eligibleNetSpendMinorUnits < 0) return null;
  return eligibleNetSpendMinorUnits;
}

export interface OrderEarningCalculation {
  wholeBoncukEarned: number;
  newCarry: BoncukFraction;
}

/**
 * BR-LOYALTY §2 / BR-LOYALTY-015 — the locked earning algorithm, now a
 * thin, module-scoped wrapper around `loyaltyPolicy.ts`'s
 * `combineCarryWithEarning` (kept as its own named export, rather than
 * calling that function directly at each call site, purely so this
 * module's own worked examples/tests have a stable, documented home). A
 * zero-eligible-spend or small-eligible-spend order may legitimately earn
 * `wholeBoncukEarned: 0` while still growing the carry fraction — that is
 * a correct, expected outcome (BR-LOYALTY §7), not an edge case to
 * special-case away.
 *
 * Verified against the correction's own locked worked example: carry
 * `2/5` (0.40 Boncuk, from 400 minor units under the default 5000/5
 * policy) plus 1000 minor units under a 5000/3 policy contributes exactly
 * `3/5` (0.60 Boncuk) more — `2/5 + 3/5 = 1` exactly, `wholeBoncukEarned:
 * 1`, `newCarry: 0/1`. No V1 spend was re-rated with V2; no V2 spend was
 * rated with V1; no fractional progress was lost.
 */
export function calculateOrderEarning(params: {
  carry: BoncukFraction;
  eligibleNetSpendMinorUnits: number;
  earningSpendMinorUnits: number;
  earningBoncukAmount: number;
}): OrderEarningCalculation {
  return combineCarryWithEarning(params.carry, params.eligibleNetSpendMinorUnits, {
    earningSpendMinorUnits: params.earningSpendMinorUnits,
    earningBoncukAmount: params.earningBoncukAmount,
  });
}

export interface DebtAwareEarningResult {
  debtPaidBoncuk: number;
  spendableCreditBoncuk: number;
  newDebtBoncuk: number;
}

/** BR-LOYALTY-014 — future earning pays down existing debt before any of it becomes spendable. */
export function applyDebtFirst(params: {
  grossBoncukEarned: number;
  boncukDebt: number;
}): DebtAwareEarningResult {
  const debtPaidBoncuk = Math.min(params.grossBoncukEarned, params.boncukDebt);
  return {
    debtPaidBoncuk,
    spendableCreditBoncuk: params.grossBoncukEarned - debtPaidBoncuk,
    newDebtBoncuk: params.boncukDebt - debtPaidBoncuk,
  };
}

export interface ProcessOrderCompletionForLoyaltyEarningResult {
  processed: boolean;
  reason: string;
  boncukEarned?: number;
}

function orderEventsCollection(db: Firestore) {
  return db.collection("orderEvents");
}

/**
 * Reads the existing account (if any) for the earning transaction,
 * tolerating a legacy pre-this-field document by safely backfilling the
 * new fields ONLY when every other field already reads as an untouched
 * zero account — otherwise fails closed rather than guessing at a
 * reconstruction. This codebase has no shipping order-completion trigger
 * yet, so no real non-zero legacy account can exist in production today —
 * this is defensive-in-depth for test/fixture data and any future
 * migration, not a path expected to fire against real customers.
 */
type AccountForEarning =
  | { status: "ok"; account: LoyaltyAccountData }
  | { status: "inconsistent-legacy-account-state" };

function resolveAccountForEarning(
  accountSnap: FirebaseFirestore.DocumentSnapshot,
  organizationId: string,
  customerId: string,
  now: Timestamp,
): AccountForEarning {
  if (!accountSnap.exists) {
    return {
      status: "ok",
      account: {
        organizationId,
        customerId,
        spendableBalance: 0,
        boncukDebt: 0,
        validOrderEntitlementBoncuk: 0,
        earningCarryNumerator: formatCarryComponent(ZERO_BONCUK_CARRY.numerator),
        earningCarryDenominator: formatCarryComponent(ZERO_BONCUK_CARRY.denominator),
        lifetimeEarned: 0,
        lifetimeRedeemed: 0,
        createdAt: now,
        updatedAt: now,
        revision: 0,
      },
    };
  }

  const raw = accountSnap.data()!;
  const hasDebt = typeof raw.boncukDebt === "number";
  const hasValidOrderEntitlement = typeof raw.validOrderEntitlementBoncuk === "number";
  const hasCarry =
    typeof raw.earningCarryNumerator === "string" && typeof raw.earningCarryDenominator === "string";
  if (hasDebt && hasValidOrderEntitlement && hasCarry) {
    return { status: "ok", account: raw as LoyaltyAccountData };
  }

  // Legacy account missing one or more of the fields above. Safe to
  // backfill to zero ONLY if every other field already reads as an
  // untouched, never-mutated zero account.
  const looksUntouched =
    raw.spendableBalance === 0 && raw.lifetimeEarned === 0 && raw.lifetimeRedeemed === 0;
  if (!looksUntouched) {
    return { status: "inconsistent-legacy-account-state" };
  }
  return {
    status: "ok",
    account: {
      ...(raw as LoyaltyAccountData),
      boncukDebt: raw.boncukDebt ?? 0,
      validOrderEntitlementBoncuk: raw.validOrderEntitlementBoncuk ?? 0,
      earningCarryNumerator:
        typeof raw.earningCarryNumerator === "string"
          ? raw.earningCarryNumerator
          : formatCarryComponent(ZERO_BONCUK_CARRY.numerator),
      earningCarryDenominator:
        typeof raw.earningCarryDenominator === "string"
          ? raw.earningCarryDenominator
          : formatCarryComponent(ZERO_BONCUK_CARRY.denominator),
    },
  };
}

/**
 * The actual business logic — called both by the trigger's fast path and
 * directly by tests, mirroring `processReservationEventForDelivery`'s own
 * pure-ish-function/thin-trigger-wrapper split.
 *
 * Cheap, pre-transaction checks (no Firestore reads needed — pure checks on
 * the event payload itself) terminate first; only a genuine earning attempt
 * opens the one atomic transaction that reads/writes the ledger entry,
 * account, and outbox flag together.
 */
export async function processOrderCompletionEventForLoyaltyEarning(
  db: Firestore,
  eventId: string,
  eventData: Record<string, unknown> | undefined,
  now: Timestamp = Timestamp.now(),
): Promise<ProcessOrderCompletionForLoyaltyEarningResult> {
  if (!eventData) return { processed: false, reason: "missing-event" };

  if (eventData.type !== "order.completed") {
    // Not an order-completion outbox record — nothing for this consumer to
    // do. Never touches rewardsEvaluated (the doc may not even have one).
    return { processed: false, reason: "not-an-order-completion-event" };
  }

  const orderId = eventData.orderId as string | undefined;
  const organizationId = eventData.organizationId as string | null | undefined;
  const customerId = eventData.customerId as string | null | undefined;
  const channel = eventData.channel as string | null | undefined;

  if (!orderId || !organizationId) {
    // A genuine data-integrity anomaly — onOrderCompleted.ts always writes
    // both fields. Log and leave rewardsEvaluated untouched (retryable),
    // never guess at a value.
    logger.error(
      `[loyaltyOrderEarning] malformed order.completed event ${eventId} — missing orderId/organizationId.`,
    );
    return { processed: false, reason: "malformed-event" };
  }

  const eventRef = orderEventsCollection(db).doc(eventId);

  if (!customerId) {
    // Guest order (dine-in QR or takeaway guest checkout) — never earns.
    await eventRef.set({ rewardsEvaluated: true }, { merge: true });
    return { processed: true, reason: "guest-order-no-customer" };
  }

  if (!isEligibleChannel(channel)) {
    // Channel pricing is not server-trusted today — a deliberate, disclosed
    // exclusion (see this file's own doc comment / BR-PRICE-002), not a
    // failure to retry.
    await eventRef.set({ rewardsEvaluated: true }, { merge: true });
    return { processed: true, reason: "channel-not-eligible-for-earning" };
  }

  const orderRef = db.collection("orders").doc(orderId);
  const membershipRef = db
    .collection(TENANT_CUSTOMERS_COLLECTION)
    .doc(`${organizationId}_${customerId}`);
  const accountRef = db.collection(LOYALTY_ACCOUNTS_COLLECTION).doc(`${organizationId}_${customerId}`);
  const policyRef = loyaltyPolicyDocRef(db, organizationId);
  const bootstrapRef = loyaltyPolicyBootstrapRef(db, organizationId);
  const ledgerEntryId = deriveLoyaltyLedgerEntryId({
    organizationId,
    customerId,
    entryType: "orderEarn",
    sourceId: orderId,
  });
  const ledgerEntryRef = db.collection(LOYALTY_LEDGER_ENTRIES_COLLECTION).doc(ledgerEntryId);

  return db.runTransaction(async (tx): Promise<ProcessOrderCompletionForLoyaltyEarningResult> => {
    // Reads first, always — mirrors completeCustomerProfile.ts's
    // established transaction discipline.
    const ledgerSnap = await tx.get(ledgerEntryRef);
    if (ledgerSnap.exists) {
      // Already applied by a prior invocation (retry, or a duplicate
      // trigger delivery) — the deterministic ledger id, not the
      // rewardsEvaluated flag, is the authoritative idempotency check.
      // Re-assert the flag in case a prior attempt crashed after this
      // point but before step 8 below, then stop — never recompute.
      tx.set(eventRef, { rewardsEvaluated: true }, { merge: true });
      return { processed: true, reason: "already-applied" };
    }

    const membershipSnap = await tx.get(membershipRef);
    if (!membershipSnap.exists) {
      // A real, expected case (not a bug) — a customer can place an order
      // before completing registration/profile. No account is created, no
      // ledger entry is written.
      tx.set(eventRef, { rewardsEvaluated: true }, { merge: true });
      return { processed: true, reason: "no-tenant-membership" };
    }

    const orderSnap = await tx.get(orderRef);
    if (!orderSnap.exists) {
      logger.error(`[loyaltyOrderEarning] order ${orderId} referenced by event ${eventId} not found.`);
      return { processed: false, reason: "order-document-missing" };
    }
    const orderData = orderSnap.data()!;
    if (orderData.status !== "completed") {
      logger.error(
        `[loyaltyOrderEarning] order ${orderId} is not status "completed" at read time (was "${String(orderData.status)}").`,
      );
      return { processed: false, reason: "order-not-completed-at-read-time" };
    }

    if (!hasServerPricingAuthority(orderData)) {
      // Security fix (2026-08-21) — an eligible channel is necessary but
      // never sufficient. Either a client-authored order that happens to
      // carry an eligible-looking channel, or a legitimate legacy order
      // that predates this field — either way, a deterministic, permanent
      // no-earn outcome, not a transient failure to retry.
      logger.warn(
        `[loyaltyOrderEarning] order ${orderId} (channel "${channel}") is on an eligible channel but has no valid server pricing-authority marker — treating as untrusted pricing provenance, never earning.`,
      );
      tx.set(eventRef, { rewardsEvaluated: true }, { merge: true });
      return { processed: true, reason: "untrusted-pricing-provenance" };
    }

    const eligibleNetSpendMinorUnits = resolveEligibleNetSpendMinorUnits(orderData);
    if (eligibleNetSpendMinorUnits === null) {
      // The mandated "do not silently approximate" escape hatch, applied
      // per-order rather than blocking the whole feature — an eligible
      // channel whose own persisted pricing snapshot is still malformed.
      logger.error(
        `[loyaltyOrderEarning] order ${orderId} (channel "${channel}") has an untrustworthy/malformed pricing.grandTotal — cannot establish earning basis.`,
      );
      return { processed: false, reason: "untrustworthy-pricing-data" };
    }

    const accountSnap = await tx.get(accountRef);
    const resolvedAccount = resolveAccountForEarning(accountSnap, organizationId, customerId, now);
    if (resolvedAccount.status === "inconsistent-legacy-account-state") {
      logger.error(
        `[loyaltyOrderEarning] account ${organizationId}_${customerId} has non-zero legacy loyalty state but is missing a required carry field — failing closed rather than guessing at a reconstruction.`,
      );
      return { processed: false, reason: "inconsistent-legacy-account-state" };
    }
    const existingAccount = resolvedAccount.account;

    // Last reads of this transaction — the organization's active policy AND
    // its trusted-bootstrap marker, resolved/auto-provisioned inside this
    // SAME transaction so the ratio used is part of the one atomic
    // operation with the account/ledger mutation below. Deliberately read
    // this late (after every early-return branch above that never needs
    // it) rather than up front with the other reads, to avoid the cost on
    // the common bail-out paths.
    const policySnap = await tx.get(policyRef);
    const bootstrapSnap = await tx.get(bootstrapRef);
    const policyResult = readLoyaltyPolicyInTransaction(policySnap, bootstrapSnap, organizationId, now);
    if (policyResult.status === "corrupt-policy-state") {
      logger.error(
        `[loyaltyOrderEarning] organization ${organizationId}'s loyaltyPolicies document has invalid/corrupt economics — failing closed rather than guessing at a rate.`,
      );
      return { processed: false, reason: "inconsistent-loyalty-policy-state" };
    }
    if (policyResult.status === "missing-live-policy") {
      logger.error(
        `[loyaltyOrderEarning] organization ${organizationId} was previously bootstrapped but its loyaltyPolicies document is now missing — failing closed rather than silently recreating the default (which could unexpectedly change live loyalty economics).`,
      );
      return { processed: false, reason: "missing-live-loyalty-policy" };
    }
    const policy = policyResult.policy;

    // Fractional Entitlement Carry — the customer's EXISTING, policy-
    // independent carry is combined as-is with THIS order's own exact
    // fractional entitlement under the policy active right now. No epoch,
    // no reset, no branch on whether the policy has changed since the
    // account last earned — see this file's own doc comment.
    const carryBefore: BoncukFraction = {
      numerator: parseCarryComponent(existingAccount.earningCarryNumerator, "loyaltyAccounts.earningCarryNumerator"),
      denominator: parseCarryComponent(
        existingAccount.earningCarryDenominator,
        "loyaltyAccounts.earningCarryDenominator",
      ),
    };
    const debtBeforeBoncuk = existingAccount.boncukDebt;

    const calc = calculateOrderEarning({
      carry: carryBefore,
      eligibleNetSpendMinorUnits,
      earningSpendMinorUnits: policy.earningSpendMinorUnits,
      earningBoncukAmount: policy.earningBoncukAmount,
    });
    const { debtPaidBoncuk, spendableCreditBoncuk, newDebtBoncuk } = applyDebtFirst({
      grossBoncukEarned: calc.wholeBoncukEarned,
      boncukDebt: debtBeforeBoncuk,
    });

    const ledgerEntry: LoyaltyLedgerEntry = {
      organizationId,
      customerId,
      entryType: "orderEarn",
      entitlementDeltaBoncuk: calc.wholeBoncukEarned,
      spendableDeltaBoncuk: spendableCreditBoncuk,
      // `0 - x` rather than unary `-x` — avoids IEEE-754 negative zero
      // (`-0`) when debtPaidBoncuk is 0; `assert.strictEqual`/Firestore
      // both distinguish -0 from 0, and a signed ledger field should never
      // carry that distinction.
      debtDeltaBoncuk: 0 - debtPaidBoncuk,
      sourceId: orderId,
      orderId,
      amountBasisMinorUnits: eligibleNetSpendMinorUnits,
      earningCarryNumeratorBefore: formatCarryComponent(carryBefore.numerator),
      earningCarryDenominatorBefore: formatCarryComponent(carryBefore.denominator),
      earningCarryNumeratorAfter: formatCarryComponent(calc.newCarry.numerator),
      earningCarryDenominatorAfter: formatCarryComponent(calc.newCarry.denominator),
      earningSpendMinorUnits: policy.earningSpendMinorUnits,
      earningBoncukAmount: policy.earningBoncukAmount,
      loyaltyPolicyVersion: policy.version,
      debtBeforeBoncuk,
      debtAfterBoncuk: newDebtBoncuk,
      redemptionValueMinorUnitsPerBoncuk: null,
      maxRedemptionBasisPoints: null,
      idempotencyKey: orderId,
      reversalOf: null,
      expiresAt: null,
      metadata: null,
    };
    // Write phase begins here — every `tx.get()` this transaction will ever
    // perform has already happened above.
    if (policyResult.needsProvisioning) {
      writeDefaultLoyaltyPolicyInTransaction(tx, db, policy);
    }
    // tx.create — defense-in-depth on top of the ledgerSnap.exists check
    // above: if a concurrent transaction wins a race this read somehow
    // missed, Firestore's own contention detection aborts and retries this
    // transaction, which then correctly takes the "already-applied" branch.
    tx.create(ledgerEntryRef, { ...ledgerEntry, createdAt: now });

    tx.set(accountRef, {
      organizationId: existingAccount.organizationId,
      customerId: existingAccount.customerId,
      spendableBalance: existingAccount.spendableBalance + spendableCreditBoncuk,
      boncukDebt: newDebtBoncuk,
      // O(1) reversal projection — a running sum of every wholeBoncukEarned
      // ever credited (before any future reversal decrements it). See
      // loyaltyReversalMath.ts's own doc comment for why this, combined
      // with the exact carry below, makes a full reversal never need to
      // read any ledger entry except the one being reversed.
      validOrderEntitlementBoncuk: existingAccount.validOrderEntitlementBoncuk + calc.wholeBoncukEarned,
      earningCarryNumerator: formatCarryComponent(calc.newCarry.numerator),
      earningCarryDenominator: formatCarryComponent(calc.newCarry.denominator),
      lifetimeEarned: existingAccount.lifetimeEarned + calc.wholeBoncukEarned,
      lifetimeRedeemed: existingAccount.lifetimeRedeemed,
      createdAt: existingAccount.createdAt,
      updatedAt: now,
      revision: existingAccount.revision + 1,
    });

    tx.set(eventRef, { rewardsEvaluated: true }, { merge: true });

    return { processed: true, reason: "earned", boncukEarned: calc.wholeBoncukEarned };
  });
}

export const onOrderEventCreatedForLoyaltyEarning = onDocumentCreated(
  "orderEvents/{eventId}",
  async (event) => {
    const snapshot = event.data;
    if (!snapshot) return;
    const db = getFirestore();
    await processOrderCompletionEventForLoyaltyEarning(
      db,
      event.params.eventId,
      snapshot.data(),
    );
  },
);
