import { test, before, after } from "node:test";
import assert from "node:assert";
import * as admin from "firebase-admin";
import { readFileSync } from "fs";
import { join } from "path";
import { migrateCanonicalCatalog, type CatalogExport } from "../catalogMigration";

/**
 * Emulator-backed tests for `migrateCanonicalCatalog` — Faz D.3.1 (Full
 * Canonical Catalog + Authenticated Takeaway Migration). Exercises the
 * exact same function `scripts/migrate_canonical_catalog.mjs` calls
 * (via `createRequire` on this file's compiled output), against the real
 * exported JSON (`scripts/data/menu_catalog_export.json`, generated by
 * `dart run tool/export_menu_catalog.dart` from the real
 * `AbakusMenuCatalog`/`LocalBowlBuilderCatalogRepository` Dart source) —
 * so this test genuinely proves the real menu migrates correctly, not a
 * synthetic stand-in shaped like it.
 *
 * Run via `npm run test:emulator` — requires
 * `scripts/data/menu_catalog_export.json` to already exist (run
 * `dart run tool/export_menu_catalog.dart` from the repo root first;
 * `npm run migrate:catalog`/`seed:dev-all` already do this).
 */

const EMULATOR_PROJECT_ID = "demo-abakus-one-emulator";
const EXPORT_PATH = join(__dirname, "..", "..", "scripts", "data", "menu_catalog_export.json");

let app: admin.app.App;
let exportData: CatalogExport;
let migrationResult: {
  categoriesWritten: number;
  productsWritten: number;
  ingredientsWritten: number;
  channelPricingPolicyWritten: boolean;
};

// Deliberately the SAME literal scope `submitTakeawayOrderRealCatalog.test.ts`
// uses for its own shared real-catalog chain: real product/ingredient
// document ids are global (`prod_mexifit_bowl`, ...), not per-test-scoped,
// so two test files independently migrating the real catalog under
// *different* scopes would race on those shared documents when `node
// --test` runs multiple files concurrently (each in its own process,
// against the one shared emulator). Converging on identical scope values
// means both files' migrations always write the same final content,
// regardless of interleaving — safe by construction, not by avoiding
// concurrency.
const SCOPE = {
  organizationId: "real-catalog-shared-org",
  restaurantId: "real-catalog-shared-restaurant",
};

before(() => {
  app = admin.initializeApp({ projectId: EMULATOR_PROJECT_ID });
  exportData = JSON.parse(readFileSync(EXPORT_PATH, "utf8")) as CatalogExport;
});

// Migrated ONCE for this whole file (not per-test) — deliberately mirrors
// `submitTakeawayOrderRealCatalog.test.ts`'s own single before()-hook
// migration into the SAME shared scope. Re-migrating on every test body
// (as this file originally did) repeatedly re-writes the same 79+64+7
// shared, globally-id'd documents throughout the whole suite's run, which
// widens the window for a cross-file write/transaction race against that
// other file's product-lookup transactions (both files' test processes run
// concurrently against one shared emulator). Migrating once, up front,
// like the other file does, minimizes that contention instead of relying
// on the two migrations' content being identical to make interleaving safe.
before(async () => {
  const db = admin.firestore();
  migrationResult = await migrateCanonicalCatalog(db, exportData, SCOPE);
});

after(async () => {
  await app.delete();
});

test("migrateCanonicalCatalog: writes every real category/product/bowl ingredient — counts match the export exactly, not a representative subset", async () => {
  const db = admin.firestore();
  const result = migrationResult;

  assert.strictEqual(result.categoriesWritten, exportData.categories.length);
  assert.strictEqual(result.productsWritten, exportData.products.length);
  assert.strictEqual(result.ingredientsWritten, exportData.bowlIngredients.length);

  // The real Abaküs menu (AbakusMenuCatalog) has 7 categories and more
  // than a small representative handful of products/ingredients — this
  // is the literal "not just ~5 seeded products" proof Faz D.3.1 exists
  // to establish. (Not hardcoding 79/64 here — the export's own length
  // is the source of truth, per direct instruction not to hardcode the
  // count; these bounds only guard against an accidentally-empty or
  // truncated export file.)
  assert.strictEqual(exportData.categories.length, 7);
  assert.ok(exportData.products.length > 50, "expected the full real menu, not a small subset");
  assert.ok(exportData.bowlIngredients.length > 30, "expected the full real ingredient catalog, not a small subset");

  const [categorySnap, productSnap, ingredientSnap] = await Promise.all([
    db.collection("menuCategories").where("organizationId", "==", SCOPE.organizationId).get(),
    db.collection("menuProducts").where("organizationId", "==", SCOPE.organizationId).get(),
    db.collection("bowlIngredients").where("organizationId", "==", SCOPE.organizationId).get(),
  ]);
  assert.strictEqual(categorySnap.size, exportData.categories.length);
  assert.strictEqual(productSnap.size, exportData.products.length);
  assert.strictEqual(ingredientSnap.size, exportData.bowlIngredients.length);
});

test("migrateCanonicalCatalog: category relationships are correct — a known real product's categoryId resolves to a real, migrated category", async () => {
  const db = admin.firestore();

  const mexifit = exportData.products.find((p) => p.id === "prod_mexifit_bowl");
  assert.ok(mexifit, "expected the real menu to still contain prod_mexifit_bowl");
  assert.strictEqual(mexifit!.categoryId, "cat_bowl");

  const categoryDoc = await db.collection("menuCategories").doc(mexifit!.categoryId).get();
  assert.ok(categoryDoc.exists);
  assert.strictEqual(categoryDoc.data()!.name, "Bowl");

  const productDoc = await db.collection("menuProducts").doc("prod_mexifit_bowl").get();
  assert.ok(productDoc.exists);
  assert.strictEqual(productDoc.data()!.categoryId, "cat_bowl");
  assert.strictEqual(productDoc.data()!.basePriceMinorUnits, 43000, "430 TL, exact minorUnits, no precision lost");
});

test("migrateCanonicalCatalog: a real beverage product migrated under cat_icecekler, exact price preserved", async () => {
  const db = admin.firestore();

  const drink = exportData.products.find((p) => p.categoryId === "cat_icecekler");
  assert.ok(drink, "expected at least one real İçecekler product");

  const doc = await db.collection("menuProducts").doc(drink!.id).get();
  assert.ok(doc.exists);
  assert.strictEqual(doc.data()!.categoryId, "cat_icecekler");
  assert.strictEqual(doc.data()!.basePriceMinorUnits, drink!.basePriceMinorUnits);
});

test("migrateCanonicalCatalog: real bowl ingredients migrated with exact prices and category grouping", async () => {
  const db = admin.firestore();

  const protein = exportData.bowlIngredients.find((i) => i.categoryId === "protein");
  assert.ok(protein, "expected at least one real protein ingredient");

  const doc = await db.collection("bowlIngredients").doc(protein!.id).get();
  assert.ok(doc.exists);
  assert.strictEqual(doc.data()!.categoryId, "protein");
  assert.strictEqual(doc.data()!.priceMinorUnits, protein!.priceMinorUnits);
  assert.strictEqual(doc.data()!.name, protein!.name);
});

test("migrateCanonicalCatalog: writes channelPricingPolicies/{restaurantId} from the real Dart policy — Faz D.3.1.1, closes the seed:dev-all REQUIRED finding", async () => {
  const db = admin.firestore();

  assert.strictEqual(migrationResult.channelPricingPolicyWritten, true);

  const policyDoc = await db.collection("channelPricingPolicies").doc(SCOPE.restaurantId).get();
  assert.ok(policyDoc.exists, "channelPricingPolicies document must exist after migration");
  const data = policyDoc.data()!;

  // Real Faz A rule (docs/business_rules.md BR-PRICE-004), sourced from
  // the real Dart InMemoryChannelPricingPolicyRepository via the export —
  // never hand-typed here a second time.
  assert.strictEqual(
    data.channelDefaultAdjustments.takeaway,
    exportData.channelPricingPolicy.channelDefaultAdjustments.takeaway,
  );
  assert.strictEqual(data.channelDefaultAdjustments.takeaway, 2000, "normal products: +20 TL on takeaway");
  assert.strictEqual(
    data.categoryOverrides.takeaway.cat_icecekler,
    exportData.channelPricingPolicy.categoryOverrides.takeaway.cat_icecekler,
  );
  assert.strictEqual(data.categoryOverrides.takeaway.cat_icecekler, 0, "İçecekler: +0 override");
});

test("migrateCanonicalCatalog: re-running with the same export is idempotent — identical counts, no duplicates", async () => {
  const db = admin.firestore();

  // Deliberately reuses SCOPE (not a separate scope) — real product/
  // ingredient document ids are global, so a separate scope here would
  // still overwrite the shared documents' organizationId/restaurantId
  // fields mid-suite-run and race against every other real-catalog test in
  // both this file and `submitTakeawayOrderRealCatalog.test.ts` (this was
  // the actual remaining cause of an intermittent cross-file failure even
  // after converging the *other* tests' scopes — this one test still used
  // its own separate scope). The `before()` hook already performed one
  // migration into SCOPE; this is genuinely a second, idempotency-proving
  // call into the exact same scope.
  const second = await migrateCanonicalCatalog(db, exportData, SCOPE);

  assert.strictEqual(migrationResult.productsWritten, second.productsWritten);

  const productSnap = await db
    .collection("menuProducts")
    .where("organizationId", "==", SCOPE.organizationId)
    .get();
  assert.strictEqual(
    productSnap.size,
    exportData.products.length,
    "exactly one document per product after two migration runs — no duplicates",
  );

  const ingredientSnap = await db
    .collection("bowlIngredients")
    .where("organizationId", "==", SCOPE.organizationId)
    .get();
  assert.strictEqual(ingredientSnap.size, exportData.bowlIngredients.length);

  // channelPricingPolicies is a single, deterministically-id'd document —
  // "no duplicates" for it means "still exactly one document, unchanged
  // content" after a second migration run, not a count comparison.
  assert.strictEqual(second.channelPricingPolicyWritten, true);
  const policyDoc = await db.collection("channelPricingPolicies").doc(SCOPE.restaurantId).get();
  assert.strictEqual(policyDoc.data()!.channelDefaultAdjustments.takeaway, 2000);
});
