// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_development.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASznbRpEB0c37-Yg3rtQsm0cnm7peAwIk',
    appId: '1:203808038574:web:cdb1e150d3f55cb463573f',
    messagingSenderId: '203808038574',
    projectId: 'abakus-one-dev',
    authDomain: 'abakus-one-dev.firebaseapp.com',
    storageBucket: 'abakus-one-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJgIeT-SK_WvtLDkK-e4Vyz8P0BMNmRM4',
    appId: '1:203808038574:android:84b204f6ca8469bc63573f',
    messagingSenderId: '203808038574',
    projectId: 'abakus-one-dev',
    storageBucket: 'abakus-one-dev.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHwS9cV7xI6wBOXRp34naKkV95_wVsf98',
    appId: '1:203808038574:ios:8abeb49e76f2e0d863573f',
    messagingSenderId: '203808038574',
    projectId: 'abakus-one-dev',
    storageBucket: 'abakus-one-dev.firebasestorage.app',
    iosBundleId: 'com.abakus.one',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHwS9cV7xI6wBOXRp34naKkV95_wVsf98',
    appId: '1:203808038574:ios:8abeb49e76f2e0d863573f',
    messagingSenderId: '203808038574',
    projectId: 'abakus-one-dev',
    storageBucket: 'abakus-one-dev.firebasestorage.app',
    iosBundleId: 'com.abakus.one',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASznbRpEB0c37-Yg3rtQsm0cnm7peAwIk',
    appId: '1:203808038574:web:44cc5ed26f6469ee63573f',
    messagingSenderId: '203808038574',
    projectId: 'abakus-one-dev',
    authDomain: 'abakus-one-dev.firebaseapp.com',
    storageBucket: 'abakus-one-dev.firebasestorage.app',
  );
}
