// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbkl4gZVpMTXUgOEgsK0Hx4WTnsXWFTfA',
    appId: '1:915484005258:web:ef16935fbfd345d5662e73',
    messagingSenderId: '915484005258',
    projectId: 'abakus-one-staging',
    authDomain: 'abakus-one-staging.firebaseapp.com',
    storageBucket: 'abakus-one-staging.firebasestorage.app',
    measurementId: 'G-X7NYG9ZETH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2vhuLB60hoK4AFlspwEFRaooFt9HGuKo',
    appId: '1:915484005258:android:b552043f766bae85662e73',
    messagingSenderId: '915484005258',
    projectId: 'abakus-one-staging',
    storageBucket: 'abakus-one-staging.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXgvu80sDbGA7Lwc2xhUGCanOd7W3FCnM',
    appId: '1:915484005258:ios:4b661d1cd01730d3662e73',
    messagingSenderId: '915484005258',
    projectId: 'abakus-one-staging',
    storageBucket: 'abakus-one-staging.firebasestorage.app',
    iosBundleId: 'com.abakus.one',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXgvu80sDbGA7Lwc2xhUGCanOd7W3FCnM',
    appId: '1:915484005258:ios:4b661d1cd01730d3662e73',
    messagingSenderId: '915484005258',
    projectId: 'abakus-one-staging',
    storageBucket: 'abakus-one-staging.firebasestorage.app',
    iosBundleId: 'com.abakus.one',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbkl4gZVpMTXUgOEgsK0Hx4WTnsXWFTfA',
    appId: '1:915484005258:web:3daec513c11c476b662e73',
    messagingSenderId: '915484005258',
    projectId: 'abakus-one-staging',
    authDomain: 'abakus-one-staging.firebaseapp.com',
    storageBucket: 'abakus-one-staging.firebasestorage.app',
    measurementId: 'G-Q0YTD5Y7DN',
  );
}
