// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBahgpxYrorq68AyanfqsT4SGca2vgE9iw',
    appId: '1:204562003593:web:0fc1e78e240708e4873858',
    messagingSenderId: '204562003593',
    projectId: 'abakusone',
    authDomain: 'abakusone.firebaseapp.com',
    storageBucket: 'abakusone.firebasestorage.app',
    measurementId: 'G-CVWVT0E25N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-RGdwKzQ8ghjaR8kqBhQYV3DgziawGJA',
    appId: '1:204562003593:android:8b56051c2c53b3ce873858',
    messagingSenderId: '204562003593',
    projectId: 'abakusone',
    storageBucket: 'abakusone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgZPK2uA-AJQllzvB-DKBQz7DajuLwxwg',
    appId: '1:204562003593:ios:3628ade0942b2147873858',
    messagingSenderId: '204562003593',
    projectId: 'abakusone',
    storageBucket: 'abakusone.firebasestorage.app',
    iosBundleId: 'com.example.abakusOneV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgZPK2uA-AJQllzvB-DKBQz7DajuLwxwg',
    appId: '1:204562003593:ios:3628ade0942b2147873858',
    messagingSenderId: '204562003593',
    projectId: 'abakusone',
    storageBucket: 'abakusone.firebasestorage.app',
    iosBundleId: 'com.example.abakusOneV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBahgpxYrorq68AyanfqsT4SGca2vgE9iw',
    appId: '1:204562003593:web:10063131dd76f46d873858',
    messagingSenderId: '204562003593',
    projectId: 'abakusone',
    authDomain: 'abakusone.firebaseapp.com',
    storageBucket: 'abakusone.firebasestorage.app',
    measurementId: 'G-7CY46CXGJY',
  );
}
