// Faz D.3.1 — full canonical catalog migration. Faz D.3.1.1: also writes
// `channelPricingPolicies/{restaurantId}` from the same export (sourced
// from the real Dart `InMemoryChannelPricingPolicyRepository`) — this
// script alone is now sufficient for `submitTakeawayOrder` to price a
// takeaway order; `seed_dev_catalog.mjs`'s own separate, hand-typed policy
// write is no longer needed for this and is not part of `seed:dev-all`'s
// chain.
//
// Reads `functions/scripts/data/menu_catalog_export.json` (generated by
// `dart run tool/export_menu_catalog.dart` from the real
// `AbakusMenuCatalog`/`LocalBowlBuilderCatalogRepository`/
// `InMemoryChannelPricingPolicyRepository` Dart source — see that script's
// own doc comment for the full "Dart is the only hand-authored source"
// sync strategy) and writes the real, full canonical catalog to Firestore
// via `src/catalogMigration.ts`'s `migrateCanonicalCatalog` (compiled
// output, imported here via `createRequire` — the robust way to consume a
// CommonJS module's named exports from an ESM `.mjs` script, rather than
// relying on static export-analysis heuristics) — the SAME function
// `functions/src/test/catalogMigration.test.ts` exercises, so this
// script and that automated test can never silently drift apart on what
// "migrate the catalog" actually does.
//
// Bound to this app's real canonical tenant chain (org-1 -> restaurant-1
// -> branch-1 — requires `npm run seed:dev-tenant` first).
//
// SAFETY: refuses to run unless FIRESTORE_EMULATOR_HOST is set. Run via:
//
//   dart run tool/export_menu_catalog.dart
//   cd functions
//   firebase emulators:exec --only firestore,functions,auth \
//     "node scripts/seed_dev_tenant.mjs && node scripts/migrate_canonical_catalog.mjs"

import admin from "firebase-admin";
import { readFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";
import { createRequire } from "module";

if (!process.env.FIRESTORE_EMULATOR_HOST) {
  console.error(
    "[migrate_canonical_catalog] FIRESTORE_EMULATOR_HOST is not set — " +
      "refusing to run against anything but the local emulator suite. " +
      'Run via `firebase emulators:exec --only firestore,functions,auth ' +
      '"node scripts/seed_dev_tenant.mjs && node scripts/migrate_canonical_catalog.mjs"`.',
  );
  process.exit(1);
}

const PROJECT_ID = process.env.GCLOUD_PROJECT || "demo-abakus-one-emulator";
const ORGANIZATION_ID = "org-1";
const RESTAURANT_ID = "restaurant-1";

const __dirname = dirname(fileURLToPath(import.meta.url));
const EXPORT_PATH = join(__dirname, "data", "menu_catalog_export.json");

const require = createRequire(import.meta.url);
const { migrateCanonicalCatalog } = require("../lib/catalogMigration.js");

const app = admin.initializeApp({ projectId: PROJECT_ID });

async function main() {
  const db = admin.firestore();

  const restaurantDoc = await db.collection("restaurants").doc(RESTAURANT_ID).get();
  if (!restaurantDoc.exists) {
    console.error(
      `[migrate_canonical_catalog] restaurants/${RESTAURANT_ID} does not exist — ` +
        "run `npm run seed:dev-tenant` first.",
    );
    process.exit(1);
  }

  let exportData;
  try {
    exportData = JSON.parse(readFileSync(EXPORT_PATH, "utf8"));
  } catch (error) {
    console.error(
      `[migrate_canonical_catalog] could not read ${EXPORT_PATH} — run ` +
        "`dart run tool/export_menu_catalog.dart` first to generate it.",
    );
    throw error;
  }

  const result = await migrateCanonicalCatalog(db, exportData, {
    organizationId: ORGANIZATION_ID,
    restaurantId: RESTAURANT_ID,
  });
  console.log(
    `[migrate_canonical_catalog] menuCategories: ${result.categoriesWritten} written.`,
  );
  console.log(
    `[migrate_canonical_catalog] menuProducts: ${result.productsWritten} written.`,
  );
  console.log(
    `[migrate_canonical_catalog] bowlIngredients: ${result.ingredientsWritten} written.`,
  );
  console.log(
    `[migrate_canonical_catalog] channelPricingPolicies/${RESTAURANT_ID}: ` +
      `${result.channelPricingPolicyWritten ? "written" : "NOT written"}.`,
  );

  // Post-write verification — proves idempotent re-runs never duplicate:
  // the collection's real document count must equal the export's own
  // item count, never more (a duplicate would only happen if a
  // non-deterministic id were used, which none of the writes above ever
  // are). channelPricingPolicies is a single, deterministically-id'd
  // document (the restaurant's own id) — existence, not count, is the
  // relevant idempotency proof for it.
  const [categoryCount, productCount, ingredientCount, policyDoc] = await Promise.all([
    db.collection("menuCategories").count().get(),
    db.collection("menuProducts").count().get(),
    db.collection("bowlIngredients").count().get(),
    db.collection("channelPricingPolicies").doc(RESTAURANT_ID).get(),
  ]);
  console.log(
    `[migrate_canonical_catalog] verified counts — categories: ${categoryCount.data().count}, ` +
      `products: ${productCount.data().count}, bowlIngredients: ${ingredientCount.data().count}, ` +
      `channelPricingPolicies/${RESTAURANT_ID} exists: ${policyDoc.exists}`,
  );

  await app.delete();
}

main().catch((error) => {
  console.error("[migrate_canonical_catalog] failed:", error);
  process.exitCode = 1;
});
