enum InventoryAuditEventType {
  ingredientCreated,
  ingredientChanged,
  inventoryItemCreated,
  stockLocationCreated,
  warehouseCreated,
  stockMovementRecorded,
  stockAdjustmentRequested,
  stockAdjustmentApproved,
  stockAdjustmentRejected,
  stockCountStarted,
  stockCountSubmitted,
  stockCountApproved,
  stockCountRejected,
  wasteRecorded,
  expiryDisposed,
}
